import { fmtNumber, fmtArea, getLanguages, getCurrencies, getGini, getCapital } from '../utils/format';

export const COMPARE_METRICS = [
  {
    key: 'population',
    label: 'Población',
    get: c => c.population ?? null,
    fmt: fmtNumber,
    numeric: true,
  },
  {
    key: 'area',
    label: 'Área',
    get: c => c.area ?? null,
    fmt: fmtArea,
    numeric: true,
  },
  {
    key: 'density',
    label: 'Densidad',
    get: c => (c.area && c.population) ? c.population / c.area : null,
    fmt: v => v != null ? `${v.toFixed(1)} hab/km²` : '—',
    numeric: true,
  },
  {
    key: 'gini',
    label: 'Índice Gini',
    get: c => getGini(c)?.value ?? null,
    fmt: v => v != null ? `${v}%` : '—',
    numeric: true,
    lowerBetter: true,
  },
  {
    key: 'timezones',
    label: 'Zonas horarias',
    get: c => c.timezones?.length ?? 0,
    fmt: v => `${v} zonas`,
    numeric: true,
  },
  {
    key: 'borders',
    label: 'Fronteras',
    get: c => c.borders?.length ?? 0,
    fmt: v => String(v),
    numeric: true,
  },
  {
    key: 'languages',
    label: 'Idiomas',
    get: c => getLanguages(c),
    fmt: v => v,
    numeric: false,
  },
  {
    key: 'currencies',
    label: 'Moneda',
    get: c => getCurrencies(c),
    fmt: v => v,
    numeric: false,
  },
  {
    key: 'capital',
    label: 'Capital',
    get: c => getCapital(c),
    fmt: v => v,
    numeric: false,
  },
  {
    key: 'region',
    label: 'Región',
    get: c => c.region || '—',
    fmt: v => v,
    numeric: false,
  },
  {
    key: 'landlocked',
    label: 'Sin litoral',
    get: c => c.landlocked ? 'Sí' : 'No',
    fmt: v => v,
    numeric: false,
  },
  {
    key: 'unMember',
    label: 'Miembro ONU',
    get: c => c.unMember ? 'Sí' : 'No',
    fmt: v => v,
    numeric: false,
  },
];
